<?php

namespace ContainerHhy0ImM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2VfWPzWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2VfWPzW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2VfWPzW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\AgencyController::index' => ['privates', '.service_locator.IwuOEF6', 'get_ServiceLocator_IwuOEF6Service', true],
            'App\\Controller\\AgencyController::show' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\HangarController::delete' => ['privates', '.service_locator.oSj2vNi', 'get_ServiceLocator_OSj2vNiService', true],
            'App\\Controller\\HangarController::edit' => ['privates', '.service_locator.oSj2vNi', 'get_ServiceLocator_OSj2vNiService', true],
            'App\\Controller\\HangarController::index' => ['privates', '.service_locator.Z2uA4KH', 'get_ServiceLocator_Z2uA4KHService', true],
            'App\\Controller\\HangarController::new' => ['privates', '.service_locator.RIjwOGn', 'get_ServiceLocator_RIjwOGnService', true],
            'App\\Controller\\HangarController::show' => ['privates', '.service_locator.TwB2bde', 'get_ServiceLocator_TwB2bdeService', true],
            'App\\Controller\\HangarController::starshipShow' => ['privates', '.service_locator.AfgR6ik', 'get_ServiceLocator_AfgR6ikService', true],
            'App\\Controller\\LoginController::index' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\MemberController::index' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\MemberController::show' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\StarshipController::delete' => ['privates', '.service_locator.G85beBR', 'get_ServiceLocator_G85beBRService', true],
            'App\\Controller\\StarshipController::edit' => ['privates', '.service_locator.G85beBR', 'get_ServiceLocator_G85beBRService', true],
            'App\\Controller\\StarshipController::index' => ['privates', '.service_locator.c_CjwZa', 'get_ServiceLocator_CCjwZaService', true],
            'App\\Controller\\StarshipController::new' => ['privates', '.service_locator.yXc32g6', 'get_ServiceLocator_YXc32g6Service', true],
            'App\\Controller\\StarshipController::show' => ['privates', '.service_locator.uZJcYxI', 'get_ServiceLocator_UZJcYxIService', true],
            'App\\Controller\\StarshipController::starshipShow' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\AgencyController:index' => ['privates', '.service_locator.IwuOEF6', 'get_ServiceLocator_IwuOEF6Service', true],
            'App\\Controller\\AgencyController:show' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\HangarController:delete' => ['privates', '.service_locator.oSj2vNi', 'get_ServiceLocator_OSj2vNiService', true],
            'App\\Controller\\HangarController:edit' => ['privates', '.service_locator.oSj2vNi', 'get_ServiceLocator_OSj2vNiService', true],
            'App\\Controller\\HangarController:index' => ['privates', '.service_locator.Z2uA4KH', 'get_ServiceLocator_Z2uA4KHService', true],
            'App\\Controller\\HangarController:new' => ['privates', '.service_locator.RIjwOGn', 'get_ServiceLocator_RIjwOGnService', true],
            'App\\Controller\\HangarController:show' => ['privates', '.service_locator.TwB2bde', 'get_ServiceLocator_TwB2bdeService', true],
            'App\\Controller\\HangarController:starshipShow' => ['privates', '.service_locator.AfgR6ik', 'get_ServiceLocator_AfgR6ikService', true],
            'App\\Controller\\LoginController:index' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\MemberController:index' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\MemberController:show' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\StarshipController:delete' => ['privates', '.service_locator.G85beBR', 'get_ServiceLocator_G85beBRService', true],
            'App\\Controller\\StarshipController:edit' => ['privates', '.service_locator.G85beBR', 'get_ServiceLocator_G85beBRService', true],
            'App\\Controller\\StarshipController:index' => ['privates', '.service_locator.c_CjwZa', 'get_ServiceLocator_CCjwZaService', true],
            'App\\Controller\\StarshipController:new' => ['privates', '.service_locator.yXc32g6', 'get_ServiceLocator_YXc32g6Service', true],
            'App\\Controller\\StarshipController:show' => ['privates', '.service_locator.uZJcYxI', 'get_ServiceLocator_UZJcYxIService', true],
            'App\\Controller\\StarshipController:starshipShow' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\AgencyController::index' => '?',
            'App\\Controller\\AgencyController::show' => '?',
            'App\\Controller\\HangarController::delete' => '?',
            'App\\Controller\\HangarController::edit' => '?',
            'App\\Controller\\HangarController::index' => '?',
            'App\\Controller\\HangarController::new' => '?',
            'App\\Controller\\HangarController::show' => '?',
            'App\\Controller\\HangarController::starshipShow' => '?',
            'App\\Controller\\LoginController::index' => '?',
            'App\\Controller\\MemberController::index' => '?',
            'App\\Controller\\MemberController::show' => '?',
            'App\\Controller\\StarshipController::delete' => '?',
            'App\\Controller\\StarshipController::edit' => '?',
            'App\\Controller\\StarshipController::index' => '?',
            'App\\Controller\\StarshipController::new' => '?',
            'App\\Controller\\StarshipController::show' => '?',
            'App\\Controller\\StarshipController::starshipShow' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AgencyController:index' => '?',
            'App\\Controller\\AgencyController:show' => '?',
            'App\\Controller\\HangarController:delete' => '?',
            'App\\Controller\\HangarController:edit' => '?',
            'App\\Controller\\HangarController:index' => '?',
            'App\\Controller\\HangarController:new' => '?',
            'App\\Controller\\HangarController:show' => '?',
            'App\\Controller\\HangarController:starshipShow' => '?',
            'App\\Controller\\LoginController:index' => '?',
            'App\\Controller\\MemberController:index' => '?',
            'App\\Controller\\MemberController:show' => '?',
            'App\\Controller\\StarshipController:delete' => '?',
            'App\\Controller\\StarshipController:edit' => '?',
            'App\\Controller\\StarshipController:index' => '?',
            'App\\Controller\\StarshipController:new' => '?',
            'App\\Controller\\StarshipController:show' => '?',
            'App\\Controller\\StarshipController:starshipShow' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
