<?php

namespace ContainerHhy0ImM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OSj2vNiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oSj2vNi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oSj2vNi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'hangar' => ['privates', '.errored..service_locator.oSj2vNi.App\\Entity\\Hangar', NULL, 'Cannot autowire service ".service_locator.oSj2vNi": it needs an instance of "App\\Entity\\Hangar" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'hangar' => 'App\\Entity\\Hangar',
        ]);
    }
}
