<?php

namespace ContainerHhy0ImM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAgencyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.yXc32g6.App\Entity\Agency' shared service.
     *
     * @return \App\Entity\Agency
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.yXc32g6": it needs an instance of "App\\Entity\\Agency" but this type has been excluded in "config/services.yaml".');
    }
}
