<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSAcVJya\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSAcVJya/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSAcVJya.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSAcVJya\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSAcVJya\App_KernelDevDebugContainer([
    'container.build_hash' => 'SAcVJya',
    'container.build_id' => 'ac65773e',
    'container.build_time' => 1728057948,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSAcVJya');
