<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU99kUmD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU99kUmD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerU99kUmD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerU99kUmD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerU99kUmD\App_KernelDevDebugContainer([
    'container.build_hash' => 'U99kUmD',
    'container.build_id' => '30b07034',
    'container.build_time' => 1732142495,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU99kUmD');
