<?php

namespace ContainerU99kUmD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YXc32g6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yXc32g6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yXc32g6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'agency' => ['privates', '.errored..service_locator.yXc32g6.App\\Entity\\Agency', NULL, 'Cannot autowire service ".service_locator.yXc32g6": it needs an instance of "App\\Entity\\Agency" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'agency' => 'App\\Entity\\Agency',
            'entityManager' => '?',
        ]);
    }
}
