<?php

namespace ContainerU99kUmD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AfgR6ikService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AfgR6ik' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AfgR6ik'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'hangar' => ['privates', '.errored..service_locator.AfgR6ik.App\\Entity\\Hangar', NULL, 'Cannot autowire service ".service_locator.AfgR6ik": it needs an instance of "App\\Entity\\Hangar" but this type has been excluded in "config/services.yaml".'],
            'starship' => ['privates', '.errored..service_locator.AfgR6ik.App\\Entity\\Starship', NULL, 'Cannot autowire service ".service_locator.AfgR6ik": it needs an instance of "App\\Entity\\Starship" but this type has been excluded in "config/services.yaml".'],
        ], [
            'doctrine' => '?',
            'hangar' => 'App\\Entity\\Hangar',
            'starship' => 'App\\Entity\\Starship',
        ]);
    }
}
