<?php

namespace ContainerU99kUmD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Z2uA4KHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Z2uA4KH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Z2uA4KH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'hangarRepository' => ['privates', 'App\\Repository\\HangarRepository', 'getHangarRepositoryService', true],
        ], [
            'hangarRepository' => 'App\\Repository\\HangarRepository',
        ]);
    }
}
