<?php

namespace Container1eHttwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_G85beBRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.G85beBR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.G85beBR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'starship' => ['privates', '.errored..service_locator.G85beBR.App\\Entity\\Starship', NULL, 'Cannot autowire service ".service_locator.G85beBR": it needs an instance of "App\\Entity\\Starship" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'starship' => 'App\\Entity\\Starship',
        ]);
    }
}
