<?php

namespace Container1eHttwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TwB2bdeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TwB2bde' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TwB2bde'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'hangar' => ['privates', '.errored..service_locator.TwB2bde.App\\Entity\\Hangar', NULL, 'Cannot autowire service ".service_locator.TwB2bde": it needs an instance of "App\\Entity\\Hangar" but this type has been excluded in "config/services.yaml".'],
        ], [
            'hangar' => 'App\\Entity\\Hangar',
        ]);
    }
}
