<?php

namespace Container1eHttwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UZJcYxIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uZJcYxI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uZJcYxI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'starship' => ['privates', '.errored..service_locator.uZJcYxI.App\\Entity\\Starship', NULL, 'Cannot autowire service ".service_locator.uZJcYxI": it needs an instance of "App\\Entity\\Starship" but this type has been excluded in "config/services.yaml".'],
        ], [
            'starship' => 'App\\Entity\\Starship',
        ]);
    }
}
