<?php

namespace Container1eHttwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHangarService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.AfgR6ik.App\Entity\Hangar' shared service.
     *
     * @return \App\Entity\Hangar
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.AfgR6ik": it needs an instance of "App\\Entity\\Hangar" but this type has been excluded in "config/services.yaml".');
    }
}
